--------------------------------------------------------
--  DDL for Table T_PERSON
--------------------------------------------------------

  CREATE TABLE "JAVAUSER"."T_PERSON" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"PASSWORD" VARCHAR2(16 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "JAVATABLESPACE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029238
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVAUSER"."SYS_C0029238" ON "JAVAUSER"."T_PERSON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "JAVATABLESPACE" ;
--------------------------------------------------------
--  DDL for Index UK_J14Q6CYANVPSJRVA5JOFE2KF5
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVAUSER"."UK_J14Q6CYANVPSJRVA5JOFE2KF5" ON "JAVAUSER"."T_PERSON" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "JAVATABLESPACE" ;
--------------------------------------------------------
--  Constraints for Table T_PERSON
--------------------------------------------------------

  ALTER TABLE "JAVAUSER"."T_PERSON" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "JAVAUSER"."T_PERSON" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "JAVATABLESPACE"  ENABLE;
 
  ALTER TABLE "JAVAUSER"."T_PERSON" ADD CONSTRAINT "UK_J14Q6CYANVPSJRVA5JOFE2KF5" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "JAVATABLESPACE"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPPERCASE_NAME
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JAVAUSER"."UPPERCASE_NAME" BEFORE
  INSERT OR
  UPDATE OF NAME ON T_PERSON FOR EACH ROW DECLARE NAMA VARCHAR2(20) ;
  BEGIN
    :NEW.NAME := UPPER(:NEW.NAME) ;
    DBMS_OUTPUT.PUT_LINE('HAS BEEN UPPERCASED AND INSERTED') ;
  END ;
/
ALTER TRIGGER "JAVAUSER"."UPPERCASE_NAME" ENABLE;
-- Unable to render TRIGGER DDL for object JAVAUSER.INSERT_UPPERCASED with DBMS_METADATA attempting internal generator.
CREATE TRIGGER INSERT_UPPERCASED BEFORE
  INSERT
    ON T_PERSON FOR EACH ROW BEGIN
  SELECT
    T_PERSON_SEQ.NEXTVAL
  INTO
    :NEW.ID
  FROM
    dual;
END;